### ISSUE TITLE
Feature Request: Delete button and functionality

### ISSUE THREAD

**Issue by SunDevil311** [sergenious/MediaBrowserAndroid#2]
## Detailed Description
Requesting the addition of a "delete" button or option within the UI, complete with the functionality of deleting the image shown. 

Delete function should include a confirmation screen to ensure the delete operation is desired. If possible, disable option for confirmation screen should be included in settings.

Also, the ability to switch to a "list view," in addition to "grid view" (the current view), would make navigation considerably easier.

## Context
While I found Media Browser very helpful, its usefulness is limited by the lack of a delete option. My particular use case is organization and cleanup of photo locations in Android.

While the visibility that Media Browser currently offers is useful, the app would provide significantly greater value and utility to myself and other users with the addition of the described feature.

## Your Environment
* Version used: Media Browser 1.1 (GH version)
* Operating System and version (desktop or mobile): Android 13 / OneUI 5.1
* Phone make and model: Samsung SM-G981U (Galaxy S20 5G)

**Comment by sergenious** [comment]
Thanks for the idea. I was already thinking about the delete button, I also miss it many times. It would be quite trivial to implement it, 5 minutes of work.

However, this opens a rabbit hole, because then it would be nice to also have an option to rename the files, copy and move them, edit the EXIF content and even include the image editor.

I would rather have Media Browser as a non-destructive read-only viewer for now. There are many file managers available, where file managing operations can be done.

But some day I might change my mind and include all the editing functionality.

**Comment by SunDevil311** [comment]
Completely understand, I respect your stance on this preference. Well reasoned explanation. Appreciate the quickk response!
